# Generated by Django 5.0.6 on 2026-07-21 23:00

import jobs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.FileField(upload_to=jobs.models.upload_path)),
                ('original_filename', models.CharField(max_length=512)),
                ('nl_prompt', models.TextField(help_text='Natural language description of the pattern')),
                ('target_column', models.CharField(max_length=255)),
                ('replacement_value', models.TextField(blank=True, default='')),
                ('regex_pattern', models.CharField(blank=True, default='', max_length=2000)),
                ('regex_source', models.CharField(blank=True, choices=[('llm', 'llm'), ('cache', 'cache'), ('fallback', 'fallback')], default='', max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=12)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_dir', models.CharField(blank=True, default='', max_length=1024)),
                ('row_count', models.BigIntegerField(blank=True, null=True)),
                ('matched_count', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
